FROM python:3.9

WORKDIR /server/src

COPY ./requirements.txt /server/requirements.txt
COPY ./.env /server/.env

RUN pip install --no-cache-dir --upgrade -r /server/requirements.txt
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get update && apt-get install libzbar0  -y

ENV PYTHONPATH=/server/src

COPY /src /server/src

EXPOSE 8000


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]